### ISSUE TITLE
Export fails with numpy array error

### ISSUE THREAD

**Issue by jeremydouglass** [dsmbgu8/image_annotate.py#3]
While testing image_annotate.py I was unable to use the export (`e` hotkey) functionality. It failed to write the .mat file to disk, with the following error:

```
Exporting 3 rois to test_rois.mat
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "/Users/username/.virtualenvs/image_annotate/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 491, in key_press
    FigureCanvasBase.key_press_event(self, key, guiEvent=event)
  File "/Users/username/.virtualenvs/image_annotate/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1847, in key_press_event
    self.callbacks.process(s, event)
  File "/Users/username/.virtualenvs/image_annotate/lib/python2.7/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(*args, **kwargs)
  File "/Users/username/.virtualenvs/image_annotate/lib/python2.7/site-packages/matplotlib/cbook.py", line 430, in __call__
    return mtd(*args, **kwargs)
  File "./image_annotate.py", line 592, in key_press_callback
    self.export_rois()
  File "./image_annotate.py", line 395, in export_rois
    idmask,groupmask = self.get_masks()
  File "./image_annotate.py", line 422, in get_masks
    maski = roi.inside(points).reshape((ny,nx))
ValueError: total size of new array must be unchanged
```

Tested with:

```
matplotlib==1.5.1
numpy==1.11.1
scipy==0.18.0
```

**Comment by dsmbgu8** [comment]
Fixed in my latest commit (4b553b0) -- the arguments to replace the call to nxutil.points_in_poly (thanks for the catch, btw) were reversed, so the output mask didn't match the expected dimensions.
